In [8]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__version__',
 '_globals',
 '_import_tools',
 '_mat',
 'abs',
 'absolute',
 'absolute_import',
 'add'

In [3]:
print(np.__version__)
np.show_config()

1.11.3
lapack_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/opt/conda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
blas_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/opt/conda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/opt/conda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
blas_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/opt/conda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
 

In [4]:
#problem 3
np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [6]:
#problem 5
Z=np.zeros(10)
Z[4]=1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [9]:
#prblem 6
Z=np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
#problem 7
Z=np.arange(50)[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [14]:
#problem 8
Z=np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#problem 9
nz=np.nonzero([1,2,3,0,0,0])
print(nz)

(array([0, 1, 2]),)


In [17]:
#problem 10
Z=np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [18]:
#problem 11
Z=np.random.random((3,3,3))
print(Z)

[[[ 0.58684422  0.76421452  0.64600006]
  [ 0.66980312  0.33155765  0.8338605 ]
  [ 0.8595388   0.06376391  0.09124505]]

 [[ 0.94247647  0.54161346  0.31017495]
  [ 0.84552882  0.16041595  0.03788194]
  [ 0.82866049  0.69739479  0.54900302]]

 [[ 0.89232039  0.65169589  0.36473493]
  [ 0.97653107  0.68714478  0.25242746]
  [ 0.11781109  0.11829837  0.15196894]]]


In [19]:
#Problem 12
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(), Z.max()
print(Zmin,Zmax)

(0.006683902285318899, 0.97885771227310692)


In [20]:
Z=np.random.random(30)
m=Z.mean()
print(m)

0.625406755927


In [21]:
Z=np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


Problem 15: 0*np.nan=nan; np.nan==np.nan=False
np.inf>np.nan=False, np.nan-np.nan=nan, 0.3==3*0.1=False

In [36]:
#problem 16
Z=np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [37]:
Z=np.zeros((8,8))
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


In [39]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [40]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [42]:
Z=np.random.random((5,5))
Z=(Z-z.min())/(Z.max()-Z.min())
print(z.mean())

0.5


In [43]:
color=np.dtype([('r',np.ubyte,1),('g',np.ubyte,1),
                ('b',np.ubyte,1),('a',np.ubyte,1)])


In [44]:
z=np.dot(np.ones((5,3)),2*np.ones((3,2)))
print(z)

[[ 6.  6.]
 [ 6.  6.]
 [ 6.  6.]
 [ 6.  6.]
 [ 6.  6.]]


In [46]:
Z=np.arange(11)
Z[(Z>3) & (Z<=8)] *=-1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [50]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [59]:
sum(np.arange(6).reshape((3,2)),0)

array([6, 9])

In [71]:
Z=np.arange(6)
Z/1/1
Z<-Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [75]:
np.array(0)/np.array(0.)

/opt/conda/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in divide
  """Entry point for launching an IPython kernel.


nan

In [79]:
def generate():
    for x in xrange(10):
        yield x
a=np.fromiter(generate(),dtype=float)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [81]:
z=np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0 1 2 3 4 5]


In [82]:
Z=np.random.random(10)
Z.sort()
print(Z)

[ 0.05907089  0.09858084  0.14788974  0.19631912  0.21899302  0.28028263
  0.40293553  0.54707202  0.55943258  0.83707103]


In [84]:
A=np.arange(5)
B=np.arange(5)*0.1*10
equal=np.allclose(A,B)
print(equal)


True


In [85]:
Z=np.random.random(10)
Z[Z.argmax()]=0
print(Z)

[ 0.15629735  0.87740766  0.0017679   0.49955024  0.04873916  0.31066324
  0.15542824  0.          0.39354445  0.94425937]


In [89]:
z=np.zeros((10,10),[('x',float),('y',float)])
z['x'],z['y']=np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
print(z)

[[(0.0, 0.0) (0.1111111111111111, 0.0) (0.2222222222222222, 0.0)
  (0.3333333333333333, 0.0) (0.4444444444444444, 0.0)
  (0.5555555555555556, 0.0) (0.6666666666666666, 0.0)
  (0.7777777777777777, 0.0) (0.8888888888888888, 0.0) (1.0, 0.0)]
 [(0.0, 0.1111111111111111) (0.1111111111111111, 0.1111111111111111)
  (0.2222222222222222, 0.1111111111111111)
  (0.3333333333333333, 0.1111111111111111)
  (0.4444444444444444, 0.1111111111111111)
  (0.5555555555555556, 0.1111111111111111)
  (0.6666666666666666, 0.1111111111111111)
  (0.7777777777777777, 0.1111111111111111)
  (0.8888888888888888, 0.1111111111111111) (1.0, 0.1111111111111111)]
 [(0.0, 0.2222222222222222) (0.1111111111111111, 0.2222222222222222)
  (0.2222222222222222, 0.2222222222222222)
  (0.3333333333333333, 0.2222222222222222)
  (0.4444444444444444, 0.2222222222222222)
  (0.5555555555555556, 0.2222222222222222)
  (0.6666666666666666, 0.2222222222222222)
  (0.7777777777777777, 0.2222222222222222)
  (0.8888888888888888, 0.222222222222

In [91]:
Z=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(Z):
    print(index,Z[index])

((0, 0), 0)
((0, 1), 1)
((0, 2), 2)
((1, 0), 3)
((1, 1), 4)
((1, 2), 5)
((2, 0), 6)
((2, 1), 7)
((2, 2), 8)


In [93]:
X=np.random.rand(5,10)
Y=X-X.mean(axis=1, keepdims=True)

[[-0.11622892  0.11199989 -0.23569154  0.07513524  0.05708911 -0.39875246
   0.41739603 -0.02118717  0.06958794  0.04065189]
 [-0.22941206  0.20418505 -0.27441058 -0.1328908  -0.2389283   0.00886543
  -0.26054386  0.26603319  0.16321712  0.4938848 ]
 [-0.42700767 -0.48108224  0.29206835 -0.08959113  0.46253038 -0.02918378
   0.30423269  0.06731954 -0.12313106  0.02384492]
 [-0.34011252  0.21689506  0.35680542 -0.08474183  0.16735031 -0.41623939
  -0.17821684  0.38069442  0.39307155 -0.49550617]
 [-0.49996217  0.10559409  0.19584557 -0.33510505 -0.22311625  0.30738302
   0.37223538  0.16755695  0.29652014 -0.38695167]]


In [96]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[:,1].argsort())

[[2 5 2]
 [9 0 8]
 [9 1 5]]
[1 2 0]


In [102]:
Z=np.random.randint(0,2,(3,10))
print(Z)
print((~Z.any(axis=0)))

[[0 1 0 1 0 1 0 1 1 1]
 [0 0 0 1 0 0 1 0 1 0]
 [0 0 1 1 1 0 0 0 0 1]]
[ True False False False False False False False False False]


In [103]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]
